import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState(15);

  const [position, setPosition] = useState("50%");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full py-10 px-20 h-screen bg-black flex">
        <div className="w-full max-w-[460px] h-full max-h-[220px] py-5 m-auto bg-[#232323] flex flex-col gap-1 justify-center">
          <div className=" w-full h-20 flex px-4 justify-between">
            <div className="flex gap-2 px-4  text-[#b1b1b1] font-bold text-xl justify-center items-center">
              <p>FRAMES</p>
              <span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                  />
                </svg>
              </span>
            </div>

            <div className="flex gap-4 px-4  text-[#b1b1b1] font-bold text-xl justify-center items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={3}
                stroke="currentColor"
                className="w-6 h-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"
                />
              </svg>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={3}
                stroke="#545454"
                className="w-6 h-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                />
              </svg>
            </div>
          </div>

          <div className=" w-full h-20 flex px-4 justify-center items-center ">
            <div className="w-full relative">
              <span
                style={{ left: position }}
                className="-translate-x-1/2 -translate-y-1/3  z-10  absolute h-6 w-6 bg-[#ffe74e]   rounded-full"
              ></span>

              <span
                style={{ left: position }}
                className=" -translate-x-1/2 -translate-y-[170%] text-xl font-bold z-10  absolute h-5 w-5 text-[#ffe74e]   rounded-full"
              >
                {value}
              </span>

              <input
                id="default-range"
                onChange={(e) => {
                  setValue(e.target.valueAsNumber);
                  setPosition((e.target.valueAsNumber / 30) * 100 + "%");
                }}
                type="range"
                min={0}
                max={30}
                value={value}
                className="w-full h-3 absolute  top-0 opacity-0 z-20 bg-[#b1b1b1]  appearance-none cursor-pointer range-sm accent-[#ffe74e] before: "
              />

              <div className="w-full h-3 bg-[#b1b1b1] relative top-0"></div>
            </div>
          </div>
          <div className="w-full h-20 flex px-4 justify-center items-center ">
            <div className="w-1/2 h-full ">
              <div className="w-fit h-full flex items-center gap-2 ">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#b1b1b1" viewBox="0 0 24 24" strokeWidth={3} stroke="#b1b1b1" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
</svg>

<svg xmlns="http://www.w3.org/2000/svg" fill="#b1b1b1" viewBox="0 0 24 24" strokeWidth={1.5} stroke="none" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
</svg>

<svg xmlns="http://www.w3.org/2000/svg" fill="#b1b1b1" viewBox="0 0 24 24" strokeWidth={1.5} stroke="none" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M21 16.811c0 .864-.933 1.405-1.683.977l-7.108-4.062a1.125 1.125 0 010-1.953l7.108-4.062A1.125 1.125 0 0121 8.688v8.123zM11.25 16.811c0 .864-.933 1.405-1.683.977l-7.108-4.062a1.125 1.125 0 010-1.953L9.567 7.71a1.125 1.125 0 011.683.977v8.123z" />
</svg>
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="#b1b1b1" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
  <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
</svg>

              </div>
            </div>


            <div className="w-1/2 h-full  ">
              <div className="w-fit h-full gap-1 ml-auto flex text-[#b1b1b1] font-extrabold text-xl justify-center items-center ">
                1:02{" "}
                <span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={3}
                    stroke="currentColor"
                    className="w-6 h-6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"
                    />
                  </svg>
                </span>{" "}
                2:02{" "}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
